### ISSUE TITLE
上传应用失败

### ISSUE THREAD

**Issue by hzjjsz** [TencentXtest/Xtest#2]
上传文件失败,log提示如下：
designed for a production environment, as it will leak
memory, and will not scale past a single process.
error when exit Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\xserverpublic\xserver_public\node_modules\express\lib\response.js:718:10)
    at ServerResponse.contentType (D:\xserverpublic\xserver_public\node_modules\express\lib\response.js:551:15)
    at ServerResponse.sendStatus (D:\xserverpublic\xserver_public\node_modules\express\lib\response.js:339:8)
    at Domain.<anonymous> (D:\xserverpublic\xserver_public\app.js:119:11)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at ReadStream.emit (events.js:139:14)
    at fs.js:1678:12
    at FSReqWrap.oncomplete (fs.js:82:15)
error when exit Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\xserverpublic\xserver_public\node_modules\express\lib\response.js:718:10)
    at ServerResponse.contentType (D:\xserverpublic\xserver_public\node_modules\express\lib\response.js:551:15)
    at ServerResponse.sendStatus (D:\xserverpublic\xserver_public\node_modules\express\lib\response.js:339:8)
    at Domain.<anonymous> (D:\xserverpublic\xserver_public\app.js:119:11)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)

在D:\xserverpublic\xserver_public\temp中生成文件是4x-0zb5rz5b0kywezrkefdgpfmu.APK
 这是为什么？

javac -version 为javac 1.8.0_31

**Comment by harryhappy** [comment]
java -version   javac -version  
下载的是2.0版本吗？
可以看看最新版本，欢迎加入加我们技术交流qq，一起探讨下

**Comment by hzjjsz** [comment]
经检查，是安装java1.8版本，在path中修改环境变量，这是电脑需要重启，xtestserver服务才能检测到JDK版本配置正确

hzjjsz@163.com

发件人： Harry
发送时间： 2016-08-21 15:32
收件人： TencentXTest/XTest
抄送： hzjjsz; Author
主题： Re: [TencentXTest/XTest] 上传应用失败 (#2)
java -version javac -version

下载的是2.0版本吗？
可以看看最新版本，欢迎加入加我们技术交流qq，一起探讨下
―

**Comment by harryhappy** [comment]
@hzjjsz   明白了，应该是java环境被写到static变量里面了。这边找对应开发确认下。
谢谢反馈问题
